### ISSUE TITLE
[Firefox 77.0.1] Inserting Line Break causes the cursor to not move

### ISSUE THREAD

**Issue by nilllzz** [ProseMirror/prosemirror#1073]
### Issue details

When inserting a Line Break for the first time in a paragraph at the end of the selection, the cursor visually does not jump to the newly inserted line.

Once you start typing after the insert, the cursor automatically moves to the originally intended position, confirming it to just be a visual glitch.

I expected the cursor behavior to mirror what it does in Chromium based browsers already, which is jump to the new line immediately after inserting the line break.

### Steps to reproduce

1. Clear the content of the editor completely
2. Position the cursor at the beginning of the document
3. Type at least a single character
4. Press `Shift + Enter` to insert a Line Break into the current paragraph
5. Observe the cursor not moving to the newly inserted line
6. Type a second character
7. Observe the cursor automatically moving to the position behind the newly typed character, and behaving like normal from now on

### ProseMirror version

_At the time of writing, I could confirm this happening on the provided editor on prosemirror.net_

However, I could also confirm this behavior with these packages used:
 - prosemirror-commands: `1.1.4`
 - prosemirror-history: `1.1.3`
 - prosemirror-inputrules: `1.1.2`
 - prosemirror-keymap: `1.1.4`
 - prosemirror-model: `1.10.0`
 - prosemirror-schema-basic: `1.1.2`
 - prosemirror-schema-list: `1.1.2`
 - prosemirror-state: `1.3.3`
 - prosemirror-view: `1.14.13`

### Affected platforms

- [ ] Firefox 77.0.1 on Ubuntu (19.10)
- [ ] Firefox 77.0.1 on Windows 10 (2004)

For any chromium based browser on any platform I did **not** see this occur (tested Chrome 83.0.4103.116 and MS Edge 83.0.478.56).

### Screenshots / Screencast (Optional)

![insert-line-break](https://user-images.githubusercontent.com/2119926/85931156-8c959180-b8c2-11ea-930f-eec774190947.gif)
(In this gif, the `Shift + Enter` keys were pressed after the word `test` was written. Then the `S` key was pressed once.)

**Comment by petermatik** [comment]
I can see similar issue with a widget decoration in an empty paragraph in Firefox 70.0.1. When I add DOM node to new paragraph, cursor is not showing until I type something.

![ff-widget-cursor_1](https://user-images.githubusercontent.com/5718113/89003341-cf062000-d2ff-11ea-8c76-0748e80c4e72.gif)
 
I am not sure if it is related but when I set `geckoKludge` to true in referenced [kludge](https://github.com/ProseMirror/prosemirror-view/commit/bd29b934ab235570d8f40c0df5941d5bdbbbc424) cursor behave as expected.

**Comment by dgreensp** [comment]
I haven't tried https://github.com/ProseMirror/prosemirror-view/commit/bd29b934ab235570d8f40c0df5941d5bdbbbc424 (I encourage doing a patch release for this, btw!), but I have a workaround that _also_ seems to improve behavior on Mac desktop Safari, where there is currently a time delay between inserting a BR and seeing the text cursor at the right spot.

The behavior I am seeing in Firefox btw (on prosemirror-view 1.15.2 without any patches or workarounds) depends on whether the editor has just been focused, or something.  If you click to put the text cursor at the end of a paragraph and focus the editor, return/backspace/return/backspace gets you the incorrect behavior, but if you type some text on the new line and then backspace over it, apparently all is good, even though there's nothing noticeably different about the selection or DOM.  Weird.  Anyway, the below hack works for the Firefox and Safari issues for me, by just resetting the DOM selection to the same range it already is.

I insert a linebreak like so:

```
  dispatch(
    state.tr
      .replaceSelectionWith(schema.nodes.linebreak.create())
      .scrollIntoView()
      .setMeta("resetSelectionHack", true)
  );
```

And then in `dispatchTransaction`:

```
        if (transaction.getMeta("resetSelectionHack")) {
          const s = document.getSelection();
          if (s) {
            const r = s.getRangeAt(0);
            if (r) {
              s.removeAllRanges();
              s.addRange(r);
            }
          }
        }
```

**Comment by marijnh** [comment]
I've released patch https://github.com/ProseMirror/prosemirror-view/commit/bd29b934ab235570d8f40c0df5941d5bdbbbc424 in prosemirror-view 1.15.3. I can't reproduce this issue anymore with that change.

**Comment by petermatik** [comment]
I am still facing the issue with the cursor disappearing when there is a widget decoration in Firefox 70.0.1. This is what I am adding on Enter to new empty paragraph: 

`let deco_blockMenu = Decoration.widget(pos, blockMenu_DOM, {key: new Date().getTime(), name: "blockMenu" , side: -1, ignoreSelection: true, stopEvent: evt => { return true; } })`

I was thinking if there a way to extend `geckoKludge` condition not only to BR node but also to include Widget decorations.

Thanks

**Comment by petermatik** [comment]
Thanks! This works for me as well.
