### ISSUE TITLE
Change the way inapplicable transform steps are handled

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#204]
Right now, they just get ignored entirely. This makes debugging them rather hard.

To the user, things may stay the same (you just don't see anything happen when some code tries to do something that isn't valid), but applying the steps should return something more useful than `null`, and when applied as part of a `Transform`, the error message should be stored somewhere for debugging purposes.

**Comment by kiejo** [comment]
I think this has been fixed with the new ```StepResult``` class that was part of the linear positions rewrite. Not sure if there's more to this issue, but otherwise we could close it.

**Comment by marijnh** [comment]
It's improved, but I'm still not very happy with the way Transform objects handle failures. I may end up punting to a simple exception-trowing schema and remove the concept of failed Transforms.
