### ISSUE TITLE
Constraining ListItem content breaks wrap, sink, and lift commands

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#357]
I'm trying to set more restrictive content constraints on a `ListItem`:
```javascript
list_item: {type: ListItem, content: "paragraph (bullet_list | ordered_list)?"},
```

Using this with the demo causes the following errors:
* Select multiple paragraphs and press `Ctrl-Shift-8`: Content does not fit in gap
* Put cursor in a list item and press `Ctrl+]`: Wrap not possible
* Put cursor in an indented list item and press `Ctrl+[`: Invalid content for node list_item

The default demo document loads correctly without errors as it fits these constraints. Looking at the given constraints the commands should theoretically be working out of the box.
It seems like the commands have been implemented with a more permissive schema in mind. But wouldn't it be easier to make them work with more restrictive constraints so that more permissive ones work out of the box without customization? Does the current system enable the implementation of these commands with the above constraints or are there some barriers to this?

**Comment by marijnh** [comment]
The first point was a bug in `canWrap`. Fixed in 94eba98.

The second indeed depended on an assumption in `list_item:sink`. Patch 4a3d49 fixes this. Though it should be noted that commands tied to node types necessarily make some assumptions about the behavior of those types, and are never going to be fully general (if you allow list items as top-level nodes, say, things will still break). This one was easy to address though.

I wasn't able to reproduce the third issue. I could get things to crash when trying to lift multiple list items out of a list entirely, which I addressed in 2765b6c0852d. But lifting from a nested list to an outer list worked for me.

**Comment by kiejo** [comment]
Thanks, this is working much better now, but I could still find some issues with the latest version which are hopefully fixable (even though I understand that these commands will never be fully general).

The first issue now throws a different error:
Select multiple paragraphs and press `Ctrl-Shift-8`: Uncaught RangeError: Wrap not possible

I now noticed that the third issue only occurs in specific situations. One way to reproduce it, is to create a list like the following, put the cursor in the list item "b", and press `Ctrl+[`:
![lis](https://cloud.githubusercontent.com/assets/152507/15504392/02fe7db8-21bf-11e6-89f4-06db205c7c24.png)
It results in the error "Invalid content for node list_item".

These are the steps to reproduce:
1. Type "* a", press `Enter`
2. Press `Ctrl+]`
3. Type "b", press `Enter`
4. Type "c", press `Up arrow`
5. Press `Ctrl+[`

**Comment by kiejo** [comment]
I just checked out the latest master and the two issues from my last comment are still reproducible :/

**Comment by marijnh** [comment]
Could you check again with current master? (Though note that it's very API incompatible to 0.7.0)

**Comment by kiejo** [comment]
Nice, I can't reproduce the issues with the current master :)

(I had to create the list using the menu, because typing `* ` results in a "Gap is not a flat range" error, which seems to be a different issue in the current master)

**Comment by marijnh** [comment]
Indeed, I broke that last week it seems. Thanks for reporting. Patch 2bd5b33 should help.
