### ISSUE TITLE
V0.14 / demo website : copy/paste and text selection issues

### ISSUE THREAD

**Issue by matthieubellon** [ProseMirror/prosemirror#497]
Hi,

We noticed several issues with copy/paste and text selection on PM v0.14 on the demo website :

#1 : windows/chrome
I can copy/cut a word from the editor, but I cannot paste it back into the same editor. An action is fired, because the history plugin display the undo button into the menu, but the pasted text does not appears. 

#2 : Windows/Chrome:
If I copy a single word from the introduction paragraph of the demo, then paste it into the middle of a paragraph in the editor, the target paragraph is splitted and a new paragraph is inserted, which contains the single copied word

#3 : Windows/IE11
Double clicking for selecting a word crash the browser.

#4: OSX/Ubuntu/Chrome 
Selecting from right to left -> the caret follow the mouse, text is not selected.

Should I create several report or are they related ?

Thanks
Matthieu

**Comment by marijnh** [comment]
Issue 4 is already fixed (upgrade to prosemirror-view 0.14.2). I'll look into the others soon.

**Comment by matthieubellon** [comment]
great, thanks

**Comment by marijnh** [comment]
The clipboard issues were an HTML parsing issue triggered by the wrapping junk Windows puts on the clipboard, fixed by https://github.com/ProseMirror/prosemirror-model/commit/dee86579504451486c0a4a230c33b0dfcaf86c17 . I couldn't reproduce the double-click crash, but I did notice that double clicking often didn't work in IE, which is fixed by https://github.com/ProseMirror/prosemirror-view/commit/87498800cfa50ef2bcabd6b39aa9d6b63fa356e8 .

I've released patch versions with these fixes. Could you take a look whether the double-click crash can still be reproduced?

**Comment by matthieubellon** [comment]
Do you want me to test on prosemirror.net ? I think that would be better.

If you did deployed on prosemirror.net bugs are still present for IE11. I managed to select a paragraph, not a word. And browser crashed ("long running script")

**Comment by marijnh** [comment]
No, the website hadn't been upgraded. It has now.

**Comment by matthieubellon** [comment]
All lights greens on IE11
- Text selection (single word, paragraph) OK
- Mouse selection (from left to right, right to left) OK
- Copy - paste from external sources OK

**Comment by marijnh** [comment]
Great!
