### ISSUE TITLE
Updating state fails to change view's DOM

### ISSUE THREAD

**Issue by bedeoverend** [ProseMirror/prosemirror#577]
When updating the state of my view, it doesn't seem to change the DOM at all.

**Browser:** Chrome 56
**Repro Code:**
```js
const { EditorState } = require("prosemirror-state")
const { EditorView } = require('prosemirror-view');
const { DOMParser, Schema, DOMSerializer } = require("prosemirror-model")
const { nodes, marks } = require("prosemirror-schema-basic")

const { doc, paragraph, text } = nodes;
const { strong, em } = marks;

let editor = document.querySelector('#editor'),
    plaintext = document.querySelector('#plaintext'),
    richtext = document.querySelector('#richtext');

let plaintextSchema = new Schema({
  nodes: { doc, paragraph, text }
});

let richtextSchema = new Schema({
  nodes: { doc, paragraph, text },
  marks: { strong, em }
});

let plaintextState = EditorState.create({
  doc: DOMParser.fromSchema(plaintextSchema).parse(editor),
  schema: plaintextSchema
});

let richtextState = EditorState.create({
  doc: DOMParser.fromSchema(richtextSchema).parse(editor),
  schema: richtextSchema
});

let view = new EditorView({ mount: editor }, {
  state: richtextState
});

plaintext.appendChild(
  DOMSerializer
    .fromSchema(plaintextSchema)
    .serializeFragment(plaintextState.doc.content)
);

richtext.appendChild(
  DOMSerializer
    .fromSchema(richtextSchema)
    .serializeFragment(richtextState.doc.content)
);

console.assert(
  editor.innerHTML === richtext.innerHTML,
  'Editor matches richtext'
); // Passes

setTimeout(() => {
  view.updateState(plaintextState);

  console.assert(
    view.state === plaintextState,
    'View has plaintext state'
  ); // Passes

  console.assert(
    editor.innerHTML === plaintext.innerHTML,
    'Editor should now match plaintext'
  ); // Fails

}, 1000);
```

Apologies for the large file. There's no error thrown, only the failed assertion that editor should match the plaintext. Manually looking at it, the editor is still showing the richtext version.

I'm pretty new to ProseMirror, so not sure if I'm missing something...perhaps because the state's have different schemas..?

**Comment by marijnh** [comment]
Right, that was a bug that occurred only when the new state used a different schema. Attached patch should solve it.

**Comment by bedeoverend** [comment]
@marijnh fantastic - thanks for the prompt response + patch!

**Comment by bedeoverend** [comment]
@marijnh Still getting this bug in another use case. I'm doing the exact same as in the above use case, but the schema I'm using is: 

```js
const { nodes } = require("prosemirror-schema-basic")

const { text } = nodes;
const inlineDoc = { content: 'inline<_>*' };

let inlineSchema = {
  doc: inlineDoc,
  text
};
```

Then doing the exact same as the JS in my first comment: works fine if I initialize the editor with that schema, but if I try to update the state that had a different schema, it fails.

Using Chrome 56. 
Prosemirror view version is: https://github.com/ProseMirror/prosemirror-view/commit/dcc9e44b516007181a406139e0042afebb6cb3c3 

---

Full test case:
```js
const { EditorView } = require('prosemirror-view');
const { DOMParser, Schema, DOMSerializer } = require("prosemirror-model")
const { nodes } = require("prosemirror-schema-basic")

const { doc, paragraph, text } = nodes;
const inlineDoc = { content: 'inline<_>*' };

let editor = document.querySelector('#editor'),
    plaintext = document.querySelector('#plaintext'),
    inline = document.querySelector('#inline');

let plaintextSchema = new Schema({
  nodes: { doc, paragraph, text }
});

let inlineSchema = new Schema({
  nodes: { doc: inlineDoc, text }
});

let plaintextState = EditorState.create({
  doc: DOMParser.fromSchema(plaintextSchema).parse(editor),
  schema: plaintextSchema
});

let inlineState = EditorState.create({
  doc: DOMParser.fromSchema(inlineSchema).parse(editor),
  schema: inlineSchema
});

let view = new EditorView({ mount: editor }, {
  state: richtextState
});

plaintext.appendChild(
  DOMSerializer
    .fromSchema(plaintextSchema)
    .serializeFragment(plaintextState.doc.content)
);

inline.appendChild(
  DOMSerializer
    .fromSchema(inlineSchema)
    .serializeFragment(inlineState.doc.content)
);

console.assert(editor.innerHTML === richtext.innerHTML, 'Editor matches richtext'); // Passes

setTimeout(() => {
  view.updateState(inlineState);
  console.assert(view.state === inlineState, 'View has inline state'); // Passes
  console.assert(editor.innerHTML === inline.innerHTML, 'Editor should now match inline'); // Fails
}, 1000);

**Comment by bedeoverend** [comment]
@marijnh taking another look it seems to be working - thanks for looking into it again, apologies for the false alarm. I'm still having some issues, but I'll nail down the minimum reproduction and report.

Also - thank you for ProseMirror, it's a fantastic library!

**Comment by bedeoverend** [comment]
Ok, @marijnh I'm trying it again and it definitely is failing for me...

This is my html
```html
<!doctype html>
<meta charset="utf8">
<body>
  <div>Editor</div>
  <div id="editor">
    <p>Hello World</p>
  </div>

  <div>Plain</div>
  <div id="plaintext"></div>

  <div>Inline</div>
  <div id="inline"></div>

  <script src="index.min.js"></script>
</body>
```
and my JS:
```js
const { EditorState } = require("prosemirror-state");
const { EditorView } = require('prosemirror-view');
const { DOMParser, Schema, DOMSerializer } = require("prosemirror-model")
const { nodes } = require("prosemirror-schema-basic")

const { doc, paragraph, text } = nodes;
const inlineDoc = { content: 'inline<_>*' };

let editor = document.querySelector('#editor'),
    plaintext = document.querySelector('#plaintext'),
    inline = document.querySelector('#inline');

let plaintextSchema = new Schema({
  nodes: { doc, paragraph, text }
});

let inlineSchema = new Schema({
  nodes: { doc: inlineDoc, text }
});

let plaintextState = EditorState.create({
  doc: DOMParser.fromSchema(plaintextSchema).parse(editor),
  schema: plaintextSchema
});

let inlineState = EditorState.create({
  doc: DOMParser.fromSchema(inlineSchema).parse(editor),
  schema: inlineSchema
});

let view = new EditorView({ mount: editor }, {
  state: plaintextState
});

plaintext.appendChild(
  DOMSerializer
    .fromSchema(plaintextSchema)
    .serializeFragment(plaintextState.doc.content)
);

inline.appendChild(
  DOMSerializer
    .fromSchema(inlineSchema)
    .serializeFragment(inlineState.doc.content)
);

console.assert(editor.innerHTML === plaintext.innerHTML, 'Editor matches plaintext'); // Passes

view.updateState(inlineState);
console.assert(view.state === inlineState, 'View has inline state'); // Passes
console.assert(editor.innerHTML === inline.innerHTML, 'Editor should now match inline'); // Fails
```

Browser: Chrome 56
Packages:
```
prosemirror-model@0.18.0
prosemirror-schema-basic@0.18.0
prosemirror-state@0.18.0
prosemirror-view@dcc9e44
```

**Comment by marijnh** [comment]
Still passing for me (with all modules at the current master branch). Maybe wait for the next release and try with that.

**Comment by bedeoverend** [comment]
Using `master` for all modules isn't working for me, but yeah I'll wait for the next release, thanks

**Comment by marijnh** [comment]
0.19.0 is out now, which includes the relevant fixes
