### ISSUE TITLE
Codeblock does not create new line on Enter | Firefox latest

### ISSUE THREAD

**Issue by jspn500** [ProseMirror/prosemirror#616]
Hey @marijnh, please have a look at the following video:
![111](https://cloud.githubusercontent.com/assets/26512812/24945260/d70ed608-1fa1-11e7-8d46-e32c0919cd02.gif)

1) create a codeblock
2) type 'foo'
3) hit Enter - cursor stays at the same position

(I'm running prosemirror.net locally, but installed latest version 0.22 )

**Comment by marijnh** [comment]
Are you using 0.20.0 by any chance? This should be fixed in 0.20.1

**Comment by jspn500** [comment]
Just tested with 0.20.3, still reproducible. I'm using Firefox 52.0.2.

**Comment by marijnh** [comment]
Works for me in Firefox 55 Linux. Are you sure you tested the right code?
